[programs.devnet]
myepicproject = "9Vxd1zX1w1B1WPitLQHxDwr9kB5bee812TdhCbNvJFzJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
